- name: Update web servers
  hosts: WebServer
  remote_user: ec2-user
  become: yes
  become_user: root

  tasks:
  - name: Install Tuned and enable throughput-performance
    shell: "{{ item }}"
    with_items:
        - yum install tuned -y
        - systemctl enable --now tuned
        - systemctl status tuned
        - tuned-adm profile throughput-performance

  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Create a default index.html page
    shell: echo "<h1>Hello, World!</h1>" > /var/www/html/index.html

  - name: Enable Apache
    service: name=httpd enabled=yes state=started
